import NavBar from 'components/NavBar'
import styles from 'styles/layout/index.module.css'

export const metadata = {
  title: 'TodoBecas',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <div className={styles.div}>
          <main className={styles.main}>
            <NavBar />
            <div className={styles.content}>{children}</div>
          </main>
        </div>
      </body>
    </html>
  )
}
